version: "3.9"
services:
  db:
    image: postgres:13-alpine
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql
    environment:
      - POSTGRES_DB=fusiondb
      - POSTGRES_USER=fusionuser
      - POSTGRES_PASSWORD=password
    ports:
      - "5459:5459"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/app
    ports:
      - 8009:8009
    command: python FusionIIIT/manage.py runserver 0.0.0.0:8009
    environment:
      - DB_HOST=db
    depends_on:
      - db
